apiVersion: v1
kind: Secret
metadata:
  name: wuda-secrets
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secrets.postgresDb | b64enc }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc }}
  JWT_KEY: {{ .Values.secrets.jwtKey | b64enc }}

  # Sekret dla front-endu
  SECRET_KEY: {{ .Values.secrets.frontendKey | b64enc }}
